### ISSUE TITLE
Single Page Applications

### ISSUE THREAD

**Issue by grahovam** [luruke/barba.js#16]
Is it possible to use this with single page js applications?

**Comment by luruke** [comment]
Hi @grahovam , what exactly do you mean with it?

If you mean to use Barba.js with a SPA frameowork (Angular, Backbone, Ember, etc.), is something I do not recommend.

Creating transitions with a SPA framework is much more easier, since all the routing is already handled by JavaScript. Refer to the documentation of your framework, I'm sure you will find way to make transition between pages.

Barba.js tries to simulate a SPA navigation using a technique called PJAX (push state ajax).

If you are using a SPA framework just for the navigation and transition between pages, probably it's better to use Barba.js, so you can benefit of a better SEO, support old browsers and keep your website working when javascript is disabled.

You can have a better understanding on how barba.js works here: http://barbajs.org/how-it-works.html

Hope it answer your question.
Cheers!
