### ISSUE TITLE
Barba.js in a webpack installation

### ISSUE THREAD

**Issue by Mellis84** [luruke/barba.js#162]
Has anyone got a basic set up?

I'm trying to use Barba.js in my Webpack setup. When I click to a new page, the .barba-container get's placed right at the bottom of the DOM.

I'm using HtmlWebpackPlugin to generate my html files, which may affect it somehow?

Cheers

**Comment by luruke** [comment]
Hey @Mellis84 ,
sorry to reply so late.

did you solved this?

**Comment by Mellis84** [comment]
Hi @luruke,
That's fine dude, haven't figured it out yet, once I get back to it and find out i'll let you know, but it has to be how my webpack config is set up using the HtmlWebpackPlugin.

Will let you know though man! 
Cheers

**Comment by javierforero** [comment]
@Mellis84  @luruke 

Hi guys,

Just wondering if you guys found a solution. I am currently building a static site using a es6-webpack-boiler plate and I am trying to get deep linking to work with barba.js. However, when I deep link to a specific url the script tag at the bottom is lost and the page loses all the css and js. 

I understand that barba only loads js once and that you can trigger certain functions upon entering a certain container, but do you guys know how this would be done with webpack (since I am using it to generate the index.js) ?

**Comment by Mellis84** [comment]
Hey dude!

This is my setup with webpack, hope this helps!

**webpack.config.js**
I require the path at the top of my file:
`const path = require('path');`

In my resolve object I create an alias:
`alias: { 
"barba": path.resolve('node_modules', 'barba.js/dist/barba.min'),
}`

**Index.js**
In my main js file I import Barba:
`import Barba from 'barba';`

I surround my barba code in a DOM ready function:
`document.addEventListener("DOMContentLoaded", () => {});`

In my html I make sure the barba container element is directly underneath the barba wrapper element, originally I had the container a few dom elements down from the wrapper and it messed things up... :P

**Comment by javierforero** [comment]
@Mellis84  gotcha. will try this out. Thanks homie

**Comment by bfred-it** [comment]
This is unrelated to webpack. You just need to have exclusive `barba-container` and `barba-wrapper` elements, don't put anything else in it. You can trick it by using `html` and `body` as wrapper and container.

**Comment by DanPen** [comment]
Thanks, @Mellis84. That works for me. Just had to change the alias from `barba.min` to `barba.min.js`.
