### ISSUE TITLE
Loading new stylesheets or scripts

### ISSUE THREAD

**Issue by gmgarrison** [luruke/barba.js#170]
A handful of my site's pages have stylesheet or script dependences that are big enough that I don't want to include them in for every page. It looks like barba doesn't load them by default but is there a way to enable loading extra CSS and JS assets?

I did look through the documentation so apologies if I missed it somewhere!

**Comment by JumpLink** [comment]
You can load scripts with [jQuery.getScript()](https://api.jquery.com/jquery.getscript/):

```
$.getScript( "ajax/test.js", function( data, textStatus, jqxhr ) {
  console.log( data ); // Data returned
  console.log( textStatus ); // Success
  console.log( jqxhr.status ); // 200
  console.log( "Load was performed." );
});
```

This is the way I do this if it's a external script I can't include to my project, but if you can, I would load all scripts and styles at the first page call, this is the way you go on single page applications.

**Comment by luruke** [comment]
@gmgarrison ,
In my opinion the best way would be to concatenate + minify all your JS/CSS and just serve a single file.

**Comment by schnoodly** [comment]
Just as a comment for the future - if you stumble across this looking for help with your script - both comments above are correct in different situations.

For instance, the specific project I'm working on right now has to make a _lot_ of calls to external databases, and potentially expand past the launch build. I'm by no way an expert, and I'm sure people have other opinions on the matter, but to argue cases for splitting the files:

## Less initial load time

The Market Futures data that I'm pulling onto this page has absolutely no use elsewhere on the site, so why make the end user load this extra unused script? For most, it's not enough code to make a difference - but for webpages that have a lot to load already, any amount you can shave off helps. If you're using some code on every page on a website, then you can easily split that off into its own piece that "loads globally," so to speak. This may add a little bit to between-page loads, though, but in terms of user experience and user capture, you want it to be _quick for them to jump in_, and _be consistent throughout the experience_.

The caveat being, if you have one page that seems to take a longer time to load, even by just a second or two, you can easily lose out on having the user go through this page - for that, we may want to use lazy loading, and/or preload the script the background. Thankfully, [Barba has prefetch](http://barbajs.org/prefetch.html), but if you need something more extensive, I can recommend looking into [PreloadJS](https://createjs.com/preloadjs) or [PACE](http://github.hubspot.com/pace/).

## "Containing" growth

What if now or in the future, a developer reuses a name or element inappropriately? What if the next person to work on this doesn't really understand not to load megabytes and megabytes of useless data? Then suddenly, you have someone loading years' worth of database information on each refresh. So, since we don't want the client coming back and being all frumpy that "we did something because it was working when HE showed me!!", we think ahead in a situation like this - we can mitigate this by splitting the javascript into their respective pages. If one page goes down, then at least the others will still work.

## Finally, Simple organization

So, I tend to get lost in long files of any type. Of course, there's things like Crtl+F, and good documentation, but that doesn't stop my brain from glazing over looking at this mountain of jumbled text. To that effect, you can also think of separating javascript files as a form of organization, _especially_ if you're working on a script-heavy project. Small quality of life things add up to keep you sane.
