### ISSUE TITLE
Google Analytics: document.title and initStateChange

### ISSUE THREAD

**Issue by andremacola** [luruke/barba.js#180]
When I use the code below the document.title of the page is not updating accordingly on GA. The GA Analytics is showing the title from previous page.

But using **newPageReady** the title is correct on GA.

BarbaJS docs recommend **initStateChange**. So.. what the difference? Can I lost some pageviews using newPageReady?

```
	Barba.Dispatcher.on('initStateChange', function() {
		if (typeof ga === 'function') {
			ga('set', 'title', document.title);
			ga('set', 'page', location.pathname);
			ga('clientTracker.set', 'title', document.title);
			ga('clientTracker.set', 'page', location.pathname);
			ga('send', 'pageview');
			ga('clientTracker.send', 'pageview');
		}
		console.log(document.title);
	});
```

**Comment by obelmont** [comment]
I believe this is because the new page has not finished loading yet. 
The pathname should work fine as the History has been updated. [See onStateChange](https://github.com/luruke/barba.js/blob/da17b49be8eb741ff3a9673652353b45c35b8e12/src/Pjax/Pjax.js#L309). 
You can see [here](https://github.com/luruke/barba.js/blob/da17b49be8eb741ff3a9673652353b45c35b8e12/src/Pjax/Pjax.js#L326) that once the load promise has been fulfilled then the onNewContainerLoaded method is called which contains the [newPageReady](https://github.com/luruke/barba.js/blob/da17b49be8eb741ff3a9673652353b45c35b8e12/src/Pjax/Pjax.js#L346) trigger.

I think that using newPageReady should be fine for the most part however I'm going to assume that if the page fails to load then you wont get any analytics on that?

**Comment by luruke** [comment]
Hello @andremacola ,
as pointed out from @obelmont in `initStateChange` the next page is not loaded yet, that means you don't have the title of the page.

You might update  the url with `initStateChange` and the title on `newPageReady`?
