### ISSUE TITLE
Form Submission Handlers on Multiple Pages

### ISSUE THREAD

**Issue by lsbyerley** [luruke/barba.js#195]
Hello, I have two contact forms on two different pages and a script that attaches an event listener to the form on submit. On fresh reload, the listener works fine, and the script uses the e.preventDefault() method. When navigating to the other page with the form, when clicking submit, the browser loads the post action in the browser, like e.preventDefault() is ignored. Is there a recommended way to handle forms on multiple pages? Basically, this is my setup.

```
function attachClickHandlers() {

    var $forms = Array.prototype.slice.call(document.querySelectorAll("#contact-form"), 0);
    if ($forms.length > 0) {
        document.getElementById("contact-form").addEventListener("submit", function(e) {
            e.preventDefault()
            //submit via ajax
        }
    }
    
}

Barba.Dispatcher.on("newPageReady", function(currentStatus, prevStatus, HTMLElementContainer, newPageRawHTML) {
    attachClickHandlers();
}
```

When navigating to another page, the preventDefault doesn't work, almost like the click handler was never attached

**Comment by lsbyerley** [comment]
@bramcordie do you have any insight on how I can solve this issue?

**Comment by bramcordie** [comment]
I haven't used them myself but http://barbajs.org/views.html might help to keep things organised. You could namespace you pages/views that contain forms and attach form specific handlers in the `onEnter` function.

On `newPageReady` the markup of the previous state is still there. Because you are targeting the forms by `id` you might be selecting the wrong one.

Wait for the `transitionCompleted` event to make sure the form of the previous state is removed.
> The transition has just finished and the old Container has been removed from the DOM.

**Comment by lsbyerley** [comment]
@bramcordie thanks, I switched the clickHandlers function over to transitionCompleted and it worked!
