### ISSUE TITLE
transitionCompleted vs newPageReady

### ISSUE THREAD

**Issue by b3nhartl3y** [luruke/barba.js#202]
Hey all,

I'm trying to reinitiate my other scripts when the "newPageReady". However the scripts don't initiate unless I'm using "transitionCompleted", and if I do the page jumps as the scripts kick in and it doesn't look great. 

Is there anything I need to do to allow "newPageReady" to work as expected. I currently have: 

First chunk is my barba code

```
var FadeTransition = Barba.BaseTransition.extend({
  start: function() {
    // As soon the loading is finished and the old page is faded out, let's fade the new page
    Promise
      .all([this.newContainerLoading, this.fadeOut()])
      .then(this.fadeIn.bind(this));
  },

  fadeOut: function() {
      return $(this.oldContainer).animate({ opacity: 0 }, 1000).promise();
  },

  fadeIn: function() {
  
    var _this = this;
    var $el = $(this.newContainer);

    $(this.oldContainer).hide();

    $el.css({
      visibility : 'visible',
      opacity : 0
    });

    $el.animate({ opacity: 1 }, 1000, function() {
          _this.done();
    });
  }
});


Barba.Pjax.getTransition = function() {

  return FadeTransition;
};

Barba.Pjax.start();
```

Then I have a function for all the additional js

```
function vendorStart() {
    <js in here>
}

vendorStart();
```

I then have my dispatcher

```
Barba.Dispatcher.on('transitionCompleted', function(currentStatus, oldStatus, container) {
    vendorStart();
});
```

As mentioned, it works on transitionCompleted but jumps, it doesnt work with 'newPageReady. Any thoughts?

Thanks for any light you can shed on this.

**Comment by swizenfeld** [comment]
were you able to find a solution for this?

**Comment by b3nhartl3y** [comment]
No yet I’m afraid

**Comment by lunelson** [comment]
I just did a project with this and found that the `newPageReady` event is a bit misleading. It fires when the DOM is ready but not yet necessarily laid out. This meant anything requiring measuring positions etc. would get incorrect values. The fix was to do it on the next 'tick' after that event fires. This might not correspond exactly to your problem but try this:

```js
Barba.Dispatcher.on("newPageReady", (currStatus, prevStatus, newContainer) => {
    setTimeout(vendorStart);
});
```

**Comment by b3nhartl3y** [comment]
Thank you I’ll try this and report back.

**Comment by Simon-Tang** [comment]
Since Barba has no control over the internals of whatever transition you may define, such behaviour could instead be triggered within your custom transition (e.g. somewhere in `fadeIn`)

**Comment by lunelson** [comment]
@Simon-Tang yes, that's the way I did it; but Barba does have this callback for `newPageReady`, which is slightly misleading in that the DOM is ready (the elements are present) but the layout (anything that needs to be measured) is not. It could easily be fixed; or another Dispatcher callback could be added

**Comment by tayler-ramsay** [comment]
Hello,

I think the issue I'm having has something to do with what you all are discussing.

I'm using a very basic fade transition on a WP site im building. Everything works great until I either enter a page with a media query or leave a page with a media query. What happens is the CSS will not load until I refresh the page. So if im entering the media query none of the styles in the media query load until I refresh the page. If im on a page with a media query and enter a page without the media query the styles retain the media query styles on the new page until I refresh the page.

here is the like to the site 
www.theheritagenews.org

here is my code:
any help would be very much appreciated. Im still fairly new to javascript.

Thanks 


document.addEventListener("DOMContentLoaded", function() {
    var FadeTransition = Barba.BaseTransition.extend({
      start: function() {
        Promise
          .all([this.newContainerLoading, this.fadeOut()])
          .then(this.fadeIn.bind(this));
      },

      fadeOut: function() {
        jQuery(this.oldContainer).toggleClass('fade-out');
    
        return new Promise(function(resolve, reject) {
            window.setTimeout(function() {
               resolve();
            }, 700);
        });
    },
      fadeIn: function() {
        jQuery(this.newContainer).toggleClass('fade-in');
        this.done();
      }
    });

    Barba.Pjax.getTransition = function() {
      return FadeTransition;
    };
});

**Comment by lunelson** [comment]
@tayler-ramsay It depends on how your CSS is loaded, but yes you probably have to do something in the `newPageReady` handler, using the Dispatcher. Basically, if you have CSS file that is only loaded on certain pages, whether via a `link` or `style` tag in the `head` or via JS, or any other meta-data or scripts or whatever, it's up to you to load it manually if you use Barba to navigate to that page. This is because Barba only swaps out content inside the `body` tag (or whatever element you defined as the "root"), while the tags in the `head` remain the same as they were on the page you started from.

**Comment by tayler-ramsay** [comment]
Lu,

I'm sorry I don't think I explained it right. All the css is loaded
together. When I go from one page to another the css all there. The issue
happens when I change from a say page,php file to a single.php template.
The css is all loaded but I have to refresh the page for the css to switch
from the page.php to the single.php template.

Thanks for the response

the site is theheritagenews.org you can see if you change from a page using
a different .php template the styling does not update till i refresh

Best regards,



*Tayler Ramsay*
*Graphic Designer*

18 Dietz Estates Drive
York PA, 17404

Phone: (717) 578-3243
Email:  ramsay.tayler@gmail.com
*www.taylerramsay.com* <http://www.taylerramsay.com/>


"Creativity is allowing yourself to make mistakes. Art is knowing which
ones to keep."

**Comment by tayler-ramsay** [comment]
Its actually the .php that is not updating

Best regards,



*Tayler Ramsay*
*Graphic Designer*

18 Dietz Estates Drive
York PA, 17404

Phone: (717) 578-3243
Email:  ramsay.tayler@gmail.com
*www.taylerramsay.com* <http://www.taylerramsay.com/>


"Creativity is allowing yourself to make mistakes. Art is knowing which
ones to keep."

**Comment by lunelson** [comment]
@tayler-ramsay no I think I can see what's going on. You have a div with the ID `#barba-wrapper` set a few levels deep in your page structure, but there are a number of classes and attributes on elements **outside of this container**, notably the body, which change when you navigate to different pages. These don't get changed when you navigate from the home page to an article page, and I think your CSS is relying on them which is why the content changes but the layout does not. 

I would say you either need to change how/where these classes are output (if this is wordpress, you can move the function that generates body classes to your barba-wrapper instead) or you need to set the barba-wrapper on one of the outer elements. Basically you need to make sure that somehow when barba swaps your content out you also get all the new context you need to trigger css changes etc.

**Comment by tayler-ramsay** [comment]
Lu,
Thank you so much for responding I will check it out today..

Best regards,



*Tayler Ramsay*
*Graphic Designer*

18 Dietz Estates Drive
York PA, 17404

Phone: (717) 578-3243
Email:  ramsay.tayler@gmail.com
*www.taylerramsay.com* <http://www.taylerramsay.com/>


"Creativity is allowing yourself to make mistakes. Art is knowing which
ones to keep."
