### ISSUE TITLE
Black listing link works then breaks

### ISSUE THREAD

**Issue by TylerOlthuizen** [luruke/barba.js#214]
I built Barba into my wordpress theme and it is working great. I have a "Gallery" page with a bunch of images and links. The links are wrapped around the image and when clicked a modal slideshow pops up. I set the class of 'no-barba' to the links and it works perfectly when I first load the page and use it. However if I then navigate to another page , say 'About Us', and then navigate back to the 'Gallery' page and proceed to click on an image, the 'no-barba' , which is still on the links, seems to be ignored and the page is then directed to the href of the image. Any thought as to why this is happening and how I can fix it?

**Comment by TylerOlthuizen** [comment]
I did get it working by reloading the scripts by doing this.

<script type="text/javascript">
  var stylesheet_directory_uri = "<?php echo get_stylesheet_directory_uri(); ?>";
   Barba.Dispatcher.on('newPageReady', () => {
      console.log(stylesheet_directory_uri);
      $.getScript( ""+stylesheet_directory_uri+"/modules/gallery/js/gallery.js", function( data, textStatus, jqxhr ) {
      });
  });
</script>

in the php page template for my gallery. Is this the best solution? it seems like my scripts are being cleared and not reloaded when I navigate away and then come back to the page.

**Comment by khaiknievel** [comment]
That happens, probably because gallery did not initialise again (reloaded) when it is navigated back. Hence, the link does not open up your modal. You just have to reinit your gallery.

```js
Barba.Dispatcher.on('newPageReady', () => {
  // Check if the gallery have not been init, then, initialise it.
})
```

Your solution maybe the easiest solution. Especially when you do not have any access to the gallery object.

Your script is not being cleared, unless it lives within your barba-container. You are right, it is just not initialise again (reloaded) when you navigate back.

Prolly you might wanna use views. newPageReady will call onReady method.
http://barbajs.org/views.html

Hope this helps.  Cheers.
