### ISSUE TITLE
Plugins don't work with barbajs Transitions active

### ISSUE THREAD

**Issue by sowearehome** [luruke/barba.js#302]
Hiya,
I am a total newbie and need some help solving this:
On my page, I'm using two plugins (Grid Kit for Wordpress & WPForms) https://sowearehome.com. I have installed Barba.js and added the Transistions feature (only on localhost at the moment). It works perfectly, except for the pages that have content created with the said plugins. The plugin content gets omitted or displayed strangely when loading the pages and only reappears/ gets displayed correctly, when I refresh the respective page. I am guessing I need to put in some additional code as in this issue here https://github.com/luruke/barba.js/issues/122, but just don't know where and what? Would be very grateful if you can point me in the right direction. Thanks!

**Comment by c0mrx** [comment]
Check out #291 and #296 

Basically, data grabbed from the AJAX call will be supped into the current page, meaning none of the javascript gets initialized again. Therefore, you'll have to manually initialize it again using barba events.

Contact forms that are generated via plugins can be tough. I use Gravity Forms on my wordpress sites and I usually get around this by keeping my forms out of the barba container so that they don't have to be reloaded at all (either by triggering them in a modal or keeping them in the nav/footer). Since most WP plugins are created without using AJAX as navigation in mind, you may run into some issues getting them to work with Barba. Hope this helps!
