### ISSUE TITLE
Improve visibility and display toggling

### ISSUE THREAD

**Issue by ZachSaucier** [luruke/barba.js#33]
Currently, if no styles are changed, after the transition completes `oldContainer` has `display: none` (it should) but `newContainer` has `visibility: hidden`. Shouldn't it be visible after `this.done()` is called?

Also, changing `visibility` is good for switching between but using `display` is better for replacing content. I think it'd be handy to use a flag to determine which property to be using so it doesn't have to be done manually each time of setup.

**Comment by luruke** [comment]
Hi @ZachSaucier ,
Thank you for your observation!

In the transition, when `.done` is called the `oldContainer` is removed from the DOM:

```javascript
done: function() {
    this.oldContainer.parentNode.removeChild(this.oldContainer);
    this.deferred.resolve();
}
```

I can add `visibility: visible` in `BaseTransition.done`, but actually should be the custom Transition responsible to make to hide the old Container and show the new one.
So, will change nothing, right?

In `visibility: hidden`, instead of `display: none` you can access to some property like height/width of the elements, and it's super useful;

You may start a slider or do other JS operation when the newContainer is attached to the DOM and the transition is not yet finished (event `onEnter` in `Views` or `newPageReady`in `Barba.Dispatcher`).

Also, with `visibility: hidden` the browser (at least Chrome) starts preloading the images, so, it's quite handy.

Hope it reply your answer, if yes, feel free to close the issue.

**Comment by ZachSaucier** [comment]
I understand your points and see the value in how it currently runs, but my original points still remain I think 😛 

It's not a big deal either way, just what I see as an improvement

**Comment by luruke** [comment]
So, basically, your idea is to make the `.done`function like this:

```javascript
done: function() {
    this.oldContainer.parentNode.removeChild(this.oldContainer);
    this.newContainer.style.visibility = 'visible';
    this.deferred.resolve();
}
```

Am I right?

If so, the default Transition `HideShowTransition` can be rewritten like:

```javascript
var HideShowTransition = BaseTransition.extend({
  start: function() {
    this.newContainerLoading.then(this.finish.bind(this));
  },

  finish: function() {
    document.body.scrollTop = 0;
    this.done();
  }
});

```

**Comment by ZachSaucier** [comment]
Yes, that is one of my proposed ideas. It keeps things simpler

**Comment by luruke** [comment]
Yo'!
Will add this in the next release!

Thank you
