### ISSUE TITLE
Unbinding function

### ISSUE THREAD

**Issue by TomS-** [luruke/barba.js#83]
Hello,

Sadly this breaks some of the 3rd party modules I use such as Skrollr. This will function on refresh, but after revisiting the page they no longer function.

I'm really wanting to use Barba to enhance the quality and feel of the websites I produce. Also I'm really interested in Google Material Design and this seems like an excellent tool to adapt that guideline. 

The thing I'm struggling with the most is if you bind things to scroll to launch a function for example; on other pages, even though they are under a different view, still fire the function as scroll is still bound. 

What is the best practice in Barba to ensure that each page actually acts like a new page from a Javascript sense.

**Comment by luruke** [comment]
Hi @TomS- 
This is the normal behaviour.

Barba.js transforms your website in a kind of Single Page Application, so you have to manage manually your JS when the page change.

In order to do that you can use barbajs events/views.

If you want to better understand how barbajs works under the hood I suggest you to read [this article](https://www.smashingmagazine.com/2016/07/improving-user-flow-through-page-transitions/).

For the rest you can have a look on the [documentation](http://barbajs.org)
