### ISSUE TITLE
Inline SVG issues

### ISSUE THREAD

**Issue by tipsy** [luruke/barba.js#93]
Hi @luruke,

I've noticed some odd behavior with inline SVGs. 
On Safari (iPhone) fill style is (sometimes) discarded when transition completes. The SVG loads properly, but on `transitionCompleted`, all paths turn black.
In Chrome on Android/Windows SVGs turn invisible on `initStateChange`.

**Comment by tipsy** [comment]
It seems `fill:url(#linear-gradient);` was the culprit. I changed it to a solid color, and everything works as expected.
```
<style>.cls-1{fill:none;}.cls-2{fill-rule:evenodd;fill:url(#linear-gradient);}</style>
<linearGradient id="linear-gradient" x1="15.47" y1="6.91" x2="27.48" y2="18.92" gradientUnits="userSpaceOnUse">
    <stop offset="0" stop-color="#2bb4d1"/>
    <stop offset="1" stop-color="#4870b4"/>
 </linearGradient>
```

**Comment by jonnyscholes** [comment]
Were you changing the gradient as part of your transition in an SVG that was already present in the DOM pre-transition? I had a similar issue recently where I was adding a class to an SVG that change the opacity of some circle elements - but Chrome refused to re-render them until I hovered over the SVG (or funnily enough toggled 'pointer-events: none/all;' at the start and end of the transition). 

I put this down to a rendering issue that was only being seen because the browser is not rendering the entire SVG fresh each time (which worked) as a result of transitioning between pages and not specifically Barba.

**Comment by tipsy** [comment]
> Were you changing the gradient as part of your transition in an SVG that was already present in the DOM pre-transition?

I only apply one class to the oldContainer and newContainer. In this particular case I darken the container:

```
.in-from-right-old-container {
    animation: darken .25s linear forwards;
    .barba-anim;
}
```

```
.barba-anim {
    overflow: hidden;
    position: absolute;
    width: 100%;
    top: 0;
    left: 0;
}
```
